# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vault',
                'verbose_name': 'Credential',
            },
        ),
    ]
