# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-04-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='account_type',
            field=models.CharField(default='web', max_length=50),
        ),
    ]
